### PR TITLE
selinux: use grep to check api supports

### LINKED ISSUE #280: selinux_state not been back ported to mainline 4.9.212+
**Describe the bug**
#245 will use selinux_state after 4.9.212+ . but it only avaliable on android common kernel. and not on mainlane. it will cause issus when using mainline 4.14/4.9 kernel

**To Reproduce**
1. build ksu on top of https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable-rc.git/tag/?h=v4.14.274
2. get some error about selinux_state not found

**Expected behavior**
fallback to alternative method automatically

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: any device using mainline kernel
 - OS: not a matter
 - Version: kernel 4.14.274

**Additional context**
works fine if i turn on the fallback method manually. i suggest add a way to control this manually by ccflags

### LINKED ISSUE #400: Use 255 instead of 337
In #324, the version check starts using `KERNEL_VERSION(4, 9, 337)`, and from the reverts after the PR merge, it seems to break many 4.9 devices, and it did break my 4.9.337 Pixel 3.

My 4.9.337 Pixel 3 `linux/version.h`:
```cpp
#define LINUX_VERSION_CODE 264703
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
```

The subversion number is only 8 bits, so it should only go up to 255. For some reason `LINUX_VERSION_CODE` follows the rule (`264703 == (4 << 16) + (9 << 8) + 255`) while `KERNEL_VERSION` doesn't. The newer `KERNEL_VERSION` is defined as follows, it seems some 4.9 devices haven't (and probably will never) been updated.
```cpp
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + ((c) > 255 ? 255 : (c)))
```

On these 4.9 devices, the relevant conditions are never met, and to adapt, we can safely make changes like:
```diff
- #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 9, 337)
+ #if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 9, 255)
- #if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 163)) || ((KERNEL_VERSION(4, 10, 0) > LINUX_VERSION_CODE) && (LINUX_VERSION_CODE  >= KERNEL_VERSION(4, 9, 337)))
+ #if (LINUX_VERSION_CODE >= KERNEL_VERSION(4, 14, 163)) || (LINUX_VERSION_CODE == KERNEL_VERSION(4, 9, 255))
```

### PR DESCRIPTION
**Pull request by PaperStrike**
This checks `selinux_state` and `current_sid` supports in a raw way. Feels more reliable than the version checks.

Supersedes #401, fixes #280, fixes #400.

### CODE REVIEW

File: kernel/selinux/Makefile [hunk 1]
```diff
@@ -2,6 +2,13 @@ obj-y += selinux.o
 obj-y += sepolicy.o
 obj-y += rules.o
 
+ifeq ($(shell grep -q " current_sid(void)" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
+ccflags-y += -DHAS_CURRENT_SID
```
Comment (tiann) [inline kernel/selinux/Makefile:6]: please prefix this MACRI with `KSU_` to avoid potential conflicts

File: kernel/selinux/rules.c [hunk 2]
```diff
@@ -22,7 +22,7 @@ static struct policydb *get_policydb(void)
 {
 	struct policydb *db;
 // selinux_state does not exists before 4.19
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(4, 9, 337)
+#ifdef USE_SELINUX_STATE
```
Comment (tiann) [inline kernel/selinux/rules.c:25]: And also, don't rely on this MARCRO on GKI kernels (version bigger than 5.10)

**Review by tiann — CHANGES_REQUESTED** [review]

File: kernel/selinux/Makefile (hunk 1 above)
Comment (PaperStrike) [reply kernel/selinux/Makefile]: https://github.com/tiann/KernelSU/pull/402/commits/47d21ee22a9f6b707246f2a06ec69814941d837f prefixed with `KSU_COMPAT_`

File: kernel/selinux/rules.c (hunk 2 above)
Comment (PaperStrike) [reply kernel/selinux/rules.c]: https://github.com/tiann/KernelSU/pull/402/commits/e4f43d1b605a1717f3993723497b81af34963508 ignored on 5.10+.
Maybe we can further optimize out the grep check in Makefile for 5.10+ by checking the `VERSION`/`PATCHLEVEL` which are set by the kernel root Makefile, but I am not quite familiar with Makefile syntax.

Comment (PaperStrike) [reply kernel/selinux/rules.c]: https://github.com/tiann/KernelSU/pull/402/commits/36909422654b36db74e0574e3ead907697098cc8 fixed.

File: kernel/selinux/Makefile [hunk 3]
```diff
@@ -2,6 +2,14 @@ obj-y += selinux.o
 obj-y += sepolicy.o
 obj-y += rules.o
 
+ifeq ($(shell [ $(VERSION) -lt 5 -o \( $(VERSION) -eq 5 -a $(PATCHLEVEL) -lt 10 \) ]; echo $$?),0)
```
Comment (tiann) [inline kernel/selinux/Makefile:5]: I think this is unnecessary, and the shell command is difficult to understand.

[the remark this answers is not in the document]
Comment (tiann) [reply kernel/selinux/Makefile:5]: I think check it in code is enough.

File: kernel/selinux/rules.c [hunk 4]
```diff
@@ -170,9 +170,7 @@ static int get_object(char *buf, char __user *user_object, size_t buf_sz,
 // reset avc cache table, otherwise the new rules will not take effect if already denied
 static void reset_avc_cache()
 {
-#if ((KERNEL_VERSION(4, 14, 0) <= LINUX_VERSION_CODE) &&                       \
-     (LINUX_VERSION_CODE < KERNEL_VERSION(4, 14, 163))) ||                     \
-	(LINUX_VERSION_CODE < KERNEL_VERSION(4, 9, 337))
+#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 10, 0)) && !defined(KSU_COMPAT_USE_SELINUX_STATE)
```
Comment (tiann) [inline kernel/selinux/rules.c:173]: we can define a macro standalone, such as:

```
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 10, 0)) || defined(KSU_COMPAT_USE_SELINUX_STATE)
#define KSU_XXXX
#endif 
```

File: kernel/selinux/Makefile [hunk 5]
```diff
@@ -2,6 +2,14 @@ obj-y += selinux.o
...
+  ifeq ($(shell grep -q " current_sid(void)" $(srctree)/security/selinux/include/objsec.h; echo $$?),0)
+  ccflags-y += -DKSU_COMPAT_HAS_CURRENT_SID
+  endif
+  ifeq ($(shell grep -q "struct selinux_state " $(srctree)/security/selinux/include/security.h; echo $$?),0)
+  ccflags-y += -DKSU_COMPAT_USE_SELINUX_STATE
```
Comment (tiann) [inline kernel/selinux/Makefile:10]: make this to KSU_COMPAT_HAS_SELINUX_STATE, and we can use

#ifdef KSU_COMPAT_HAS_SELINUX_STATE || version > 5.10
#define KSU_COMPAT_USE_SELINUX_STATE
#endif

**Review by tiann — CHANGES_REQUESTED** [review]

File: kernel/selinux/Makefile (hunk 3 above)
Comment (PaperStrike) [reply kernel/selinux/Makefile]: Reverted in https://github.com/tiann/KernelSU/pull/402/commits/468120cb099b8489d8a157887431a36a733f675d

File: kernel/selinux/rules.c (hunk 4 above)
Comment (PaperStrike) [reply kernel/selinux/rules.c]: https://github.com/tiann/KernelSU/pull/402/commits/6bf07bf51559512439290da07af1381faa63de14 done.

**Review by tiann — APPROVED** [review]

File: kernel/selinux/Makefile (hunk 5 above)
Comment (PaperStrike) [reply kernel/selinux/Makefile]: https://github.com/tiann/KernelSU/pull/402/commits/6bf07bf51559512439290da07af1381faa63de14 done.

I put it in `selinux.h`, since both `selinux.c` and `rules.c` have the same check. Let me know if it is inappropriate.
